[project]
name = "stock-ml-forecast"
version = "0.1.0"
description = "Stock machine learning forecast project"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "tensorflow>=2.21.0",
    "numpy",
    "pandas",
    "requests",
    "scikit-learn",
    "yfinance",
    "lxml>=6.1.3",
    "pyarrow>=25.0.1",
]

[project.scripts]
stock-ml-forecast = "stock_ml_forecast:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
